### ISSUE TITLE
`ref struct` types should not be used as type arguments.

### ISSUE THREAD

**Issue by brian-reichle** [DotNetAnalyzers/ReflectionAnalyzers#153]
Split off from https://github.com/DotNetAnalyzers/ReflectionAnalyzers/issues/152#issuecomment-427687185

The compiler does not allow ref struct types to be used as generic type arguments because that could be used to allow `Span<>`s onto the heap. Should have a rule to provide similar checks for reflection.

```csharp
void Main()
{
    // Error ref structs cannot be generic type arguments regardless of constraints.
    typeof(List<>).MakeGenericType(typeof(Span<int>));

    // typeof(List<Span<int>>) <-- CS0306: The type 'Span<int>' may not be used as a type argument
}
```

**Comment by JohanLarsson** [comment]
We save this for the next major release of roslyn unless we figure out a way to dig out the info from the existing bits.

**Comment by JohanLarsson** [comment]
```cs

            [Test]
            public void RefStruct()
            {
                var refStruct = @"
namespace RoslynSandbox
{
    public ref struct RefStruct
    {
        public int Value;
    }
}";
                var code = @"
namespace RoslynSandbox
{
    using System;

    public class Foo<T>
    {
        public static object Get() => typeof(Foo<>).MakeGenericType(↓typeof(RefStruct));
    }
}";
                var message = "The argument typeof(RefStruct), on 'RoslynSandbox.Foo<>' violates the constraint of type 'T'.";
                AnalyzerAssert.Diagnostics(Analyzer, ExpectedDiagnostic.WithMessage(message), refStruct, code);
            }
```

Moving this test from REFL031 test to here.

**Comment by jnm2** [comment]
@JohanLarsson `ref struct` desugars to `[IsByRefLike]` on the struct.

https://sharplab.io/#v2:EYLgHgbALANALiAlgGwD4AEDMACATgUwDNsBnOXAVwGM5sAVfM7Ab2wF8BYAKCA=

This way you can support VS 2017.

**Comment by jnm2** [comment]
###### Re: https://gitter.im/DotNetAnalyzers/ReflectionAnalyzers?at=5bbdbce8600c5f642382bace

@JohanLarsson 

>  `MakeGenericType` does not throw when passing in `typeof(RefStruct)`

@brian-reichle 

> I would be tempted to consider that an oversight in the reflection api. If you try to construct a `C<RefStruct>` in code (without reflection) then the C# compiler will consider it an error. This is to ensure that things like `Span<>`can't slip onto the heap (where bad things happen).

Hmm... my position would be that reflection is not about the C# type system, only about the CLR type system. To the extent that they differ, I don't want this analyzer to enforce any C# rules. At the point where you use reflection, you're *only* targeting the CLR type system and you can already do things that are incorrect according to C#.

**Comment by brian-reichle** [comment]
`Span<>` cannot be in the heap because it uses an internal pointer and the GC only supports internal pointers on the stack/in registers. The `ref struct` concept is just a way of enforcing this. The reflection api might allow us to create a type representing `List<Span<int>>` but creating an instance of such a type (or calling a method similarly tainted) may cause your application to burst into flames.

**Comment by JohanLarsson** [comment]
>This way you can support VS 2017.

Do you have a sample getting the attribute? From my digging it looks like it is filtered out.

**Comment by JohanLarsson** [comment]
Maybe it should be a separate rule as @brian-reichle suggests, then it can be disabled if it gets annoying.

**Comment by jnm2** [comment]
@brian-reichle However, there is a chance that the method or class just happens not to ever cause a `T` to go on the heap, making this totally safe even though C# isn't complex enough to enforce safety around this scenario yet.

In the cases where an analyzer would ever be able to detect this, wouldn't the usage also be very deliberate? Not sure there's a huge ROI here.

As long as the rule itself doesn't mention C#, I'm fine with it. "Using this type to create an instance may may destabilize the runtime."

@JohanLarsson 

> Do you have a sample getting the attribute? From my digging it looks like it is filtered out.

Sorry, mine's MetadataReader-based. If Roslyn is filtering that one out, that means they have code specially looking for it. If we find that code, we might find that it's stashing that info somewhere else.

**Comment by brian-reichle** [comment]
The provided sample does throw an exception under .Net Core

```csharp
static void Main(string[] args)
{
    typeof(List<>).MakeGenericType(typeof(Span<int>));
}
```

> 'The generic type 'System.Collections.Generic.List`1' was used with an invalid instantiation in assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.'

```
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at CoreTestApplication.Program.Main(String[] args) in C:\Working\Scratch\CoreTestApplication\CoreTestApplication\Program.cs:line 10
```

**Comment by jnm2** [comment]
I see. Same for MakeGenericMethod?

**Comment by brian-reichle** [comment]
yep

```csharp
static void Main(string[] args)
{
    typeof(Program)
        .GetMethod(
            "Foo",
            BindingFlags.NonPublic | BindingFlags.Static)
        .MakeGenericMethod(typeof(Span<int>));
}

static void Foo<T>()
{
}
```

> 'An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)'

```
   at System.RuntimeMethodHandle.GetStubIfNeeded(RuntimeMethodHandleInternal method, RuntimeType declaringType, RuntimeType[] methodInstantiation)
   at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
   at CoreTestApplication.Program.Main(String[] args) in C:\Working\Scratch\CoreTestApplication\CoreTestApplication\Program.cs:line 10
```

**Comment by jnm2** [comment]
Thanks. Since this is enforced by the CLR, the analyzer would be a perfect fit.

**Comment by JohanLarsson** [comment]
https://github.com/dotnet/roslyn/issues/30426
