### ISSUE TITLE
NRE in 0.1.15-dev 

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/ReflectionAnalyzers#172]
0.1.15-dev:

> AD0001 Analyzer 'ReflectionAnalyzers.GetTypeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
> 
> ```
> Exception occurred with following context:
> SyntaxNode: .GetType() [InvocationExpressionSyntax]@[1220..1230) (30,70)-(30,80)
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at ReflectionAnalyzers.GetTypeAnalyzer.Handle(SyntaxNodeAnalysisContext context)
>    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__44`1.<ExecuteSyntaxNodeAction>b__44_0(ValueTuple`2 data)
>    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
> ```

The line in question:

```c#
var currentType = property.GetValue(context.Instance)?.GetType();
```

**Comment by jnm2** [comment]
The crash disappears if I remove the `?`.
