### ISSUE TITLE
Bug in ActivatorAnalyzer

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/ReflectionAnalyzers#202]
```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'ReflectionAnalyzers.ActivatorAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Operation is not valid due to the current state of the object.'.	Gu.Reactive		1	Active	Analyzer 'ReflectionAnalyzers.ActivatorAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Gu.Reactive
SyntaxTree: C:\Git\_GuOrg\Gu.Reactive\Gu.Reactive\Collections\ReadOnlyViews\Mapping\Mapper.cs
SyntaxNode: Activator.CreateInstance( typeof ... [InvocationExpressionSyntax]@[2232..2396) (54,46)-(56,42)

System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Construct(ImmutableArray`1 arguments, Boolean unbound)
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.ConstructWithoutModifiers(ImmutableArray`1 arguments, Boolean unbound)
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Microsoft.CodeAnalysis.INamedTypeSymbol.Construct(ITypeSymbol[] arguments)
   at ReflectionAnalyzers.Type.TryGet(ExpressionSyntax expression, SyntaxNodeAnalysisContext context, PooledSet`1 visited, ITypeSymbol& result, ExpressionSyntax& source)
   at ReflectionAnalyzers.ActivatorAnalyzer.TryGetCreatedType(IMethodSymbol createInstance, InvocationExpressionSyntax invocation, SyntaxNodeAnalysisContext context, ITypeSymbol& createdType, ExpressionSyntax& typeSource)
   at ReflectionAnalyzers.ActivatorAnalyzer.Handle(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__44`1.<ExecuteSyntaxNodeAction>b__44_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

**Comment by JohanLarsson** [comment]
Minimal repro

```cs
            [Test]
            public void Issue202()
            {
                var code = @"
namespace RoslynSandbox
{
    using System;
    using System.Reflection;

    internal static class C
    {
        internal static object Create<T1, T2>()
        {
            if (!typeof(T1).IsValueType &&
                !typeof(T2).IsValueType)
            {
                return Activator.CreateInstance(typeof(C<,>).MakeGenericType(typeof(T1), typeof(T2)));
            }

            return null;
        }
    }

    internal class C<T1, T2>
        where T1 : class
        where T2 : class
    {
    }
}";

                AnalyzerAssert.Valid(Analyzer, Descriptor, code);
            }
```
